### ISSUE TITLE
Not possible to delete field values

### ISSUE THREAD

**Issue by kunkku** [nsd20463/pwsafe#18]
Once set, it is not possible to remove the value of a field (e.g. group or notes) using the `--edit` command. Attempting to use an empty value results in the original value being used.

**Comment by nsd20463** [comment]
Yeah, that's a problem with the text based user interface. Using 'Enter' to indicate 'no change' is more often what you want.
You can work around this by giving a dummy value like a single space. That's not exactly the same, but might be good enough for your purposes.

Do you have any good ideas how to have the user indicate, while editing an entry, that they want to delete a field rather than leave it be?

**Comment by microe** [comment]
Maybe have an inbetween step like "change password ?"? I am thinking of something like this:
```
change notes (y/n/d) ? [n]
```

**Comment by nsd20463** [comment]
OK. Let me see what I can do.

**Comment by nsd20463** [comment]
Done

**Comment by kunkku** [comment]
How about deleting the group value?

**Comment by nsd20463** [comment]
it's now universal. only the name can't be deleted.
